name = "twrelay"
main = "worker.js"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]
